name: CI
on: push

jobs:
  check-solutions:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.0", "1.1.15", "1.2.1"]
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      
      - name: View poetry --help
        run: poetry --help
      
      - name: Install dependencies
        shell: bash
        run: python -m poetry install
      
      - name: Test with pytest
      run: |
        python -m poetry run python -m pytest -v tests